### ISSUE TITLE
Write a well drafted and engaging blog

### ISSUE THREAD

**Issue by JainishaPathak** [CSI-DMCE-2023/NON-CODE-HacktoberFest-2023#11]
Write a well drafted and engaging blog of any CSI event that you have attended. add images if available . Express your entire experience, thoughts and feedback . 

publish the blog here 
https://www.blogger.com/blog/post/edit/6652842905689488670/8165315813756377123
share the link

**Comment by tanvirkamble** [comment]
assign me

**Comment by pranavnr** [comment]
I'd appreciate it if you could entrust me with this matter.

**Comment by Karan2310** [comment]
> assign me

Okay!

**Comment by ghost** [comment]
I am interested in creating a blog for the github seminar. Please assign me this task
